### ISSUE TITLE
Parquet Metadata Store deduplication on filter defaults to true instead of false

### ISSUE THREAD

**Issue by gallushi** [xskipper-io/xskipper#70]
Deduplication during filtering is documented as `false` by default, but accidentally configured as `true` by [default](https://github.com/xskipper-io/xskipper/blob/96f4ff637c734bc3ae4dcdf1fec836777b8d2c18/src/main/scala/io/xskipper/metadatastore/parquet/ParquetMetadataStoreConf.scala#L137).
This does not affect query results in any way, but may degrade performance in some cases, as it causes a `distinct` to be run on the metadata.
to disable dedup during filtering, set `io.xskipper.parquet.filter.dedup` to `false`

From the next release (the one following `1.2.3`) will be disabled by default.

**Comment by guykhazma** [comment]
fixed in #72
